language: php

dist: trusty
sudo: false

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.2
    - php: nightly
  allow_failures:
    - php: nightly

env:
  - SYMFONY_VERSION="4.0.*" DB=mysql

before-install:
  - composer self-update

install:
  - composer install
  - cp .env.dist .env
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test
  - php bin/console doctrine:fixtures:load -n --env=test

script:
  - phpunit

