language: php

dist: trusty
sudo: required

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache/files

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.2
    - php: nightly
  allow_failures:
    - php: nightly

env:
  - SYMFONY_VERSION="4.0.*" DB=mysql

before-install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('Pa33w0rd') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade
  - sudo service mysql restart
  - composer self-update

install:
  - composer install
  - cp .env.dist .env
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test
  - php bin/console doctrine:fixtures:load -n --env=test

script:
  - phpunit
